---
- name: Install Wordpress, Nginx and Node_Exporter
  hosts: WebServer MySQLSlave
  remote_user: root
  roles:
#  - nginx
#  - mysql
#  - wordpress
#  - node_exporter
  - filebeat
- name: Install ELK
  hosts: elk
  remote_user: root
  roles:
    - elk

#- name: Install Prometheus
#  hosts: Prometheus
#  remote_user: root
#  roles:
#    - prometheus
#    - grafana

...
