---
- name: Install Wordpress, Nginx and Node_Exporter
  hosts: WebServer MySQLSlave
  remote_user: root
  roles:
#  - nginx
  - mysql
#  - wordpress
#  - node_exporter

#- name: Install MySQLMaster, MySQLSlave
#  hosts: WebServer
#  remote_user: root
#  roles:
#    - node_exporter

- name: Install Prometheus
  hosts: Prometheus
  remote_user: root
  roles:
#    - prometheus
#    - grafana

...
